### ISSUE TITLE
Warning messages are partially hidden by header bar

### ISSUE THREAD

**Issue by doxanthropos** [hrz-unimr/Ilias.SEBPlugin#1]
Hello!
Nice to see this new and beautiful new version of the plugin.
One little thing that might be an issue is the positioning of the header bar in relation to possible warning messages from Ilias, like the ones seen when a student tries to answer a numerical question with a non-numerical answer.
I'll attach a screenshot to clarify, what I mean.
Thanks already for your effort on making this very useful plugin.

![warning-not-visible](https://cloud.githubusercontent.com/assets/2058212/18753845/e5867af6-80e6-11e6-9caf-adf2262c9ebe.png)

Knut Jackowski
Universität Koblenz-Landau
Institut für Wissensmedien

**Comment by eqsoft** [comment]
Thank you Knut!
Fixed in trunk, will be patched back to 5.0 and 5.1 in a few days
