### ISSUE TITLE
trunk crashes on Ilias 5.2

### ISSUE THREAD

**Issue by sbaecker** [hrz-unimr/Ilias.SEBPlugin#3]
Missing argument 1 for ilSEBUIHookGUI::setUserGUI(), called in /var/www/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/SEB/classes/class.ilSEBUIHookGUI.php on line 208 and defined

**Comment by eqsoft** [comment]
Thank you Stefan!
Fixed.
